name: Main

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build site
      run: npm run build
    - name: Deploy site to S3
      run: npm run deploy
